/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AutoBackupResponse } from './AutoBackupResponse';
import {
    AutoBackupResponseFromJSON,
    AutoBackupResponseFromJSONTyped,
    AutoBackupResponseToJSON,
    AutoBackupResponseToJSONTyped,
} from './AutoBackupResponse';

/**
 * 
 * @export
 * @interface AutoBackupListResponse
 */
export interface AutoBackupListResponse {
    /**
     * 
     * @type {number}
     * @memberof AutoBackupListResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof AutoBackupListResponse
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof AutoBackupListResponse
     */
    total?: number;
    /**
     * 
     * @type {Array<AutoBackupResponse>}
     * @memberof AutoBackupListResponse
     */
    items?: Array<AutoBackupResponse>;
}

/**
 * Check if a given object implements the AutoBackupListResponse interface.
 */
export function instanceOfAutoBackupListResponse(value: object): value is AutoBackupListResponse {
    return true;
}

export function AutoBackupListResponseFromJSON(json: any): AutoBackupListResponse {
    return AutoBackupListResponseFromJSONTyped(json, false);
}

export function AutoBackupListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoBackupListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'total': json['total'] == null ? undefined : json['total'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(AutoBackupResponseFromJSON)),
    };
}

export function AutoBackupListResponseToJSON(json: any): AutoBackupListResponse {
    return AutoBackupListResponseToJSONTyped(json, false);
}

export function AutoBackupListResponseToJSONTyped(value?: AutoBackupListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'limit': value['limit'],
        'total': value['total'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(AutoBackupResponseToJSON)),
    };
}

