/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClientSignalResponse } from './ClientSignalResponse';
import {
    ClientSignalResponseFromJSON,
    ClientSignalResponseFromJSONTyped,
    ClientSignalResponseToJSON,
    ClientSignalResponseToJSONTyped,
} from './ClientSignalResponse';

/**
 * 
 * @export
 * @interface SignalListResponse
 */
export interface SignalListResponse {
    /**
     * 
     * @type {number}
     * @memberof SignalListResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof SignalListResponse
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof SignalListResponse
     */
    total?: number;
    /**
     * 
     * @type {Array<ClientSignalResponse>}
     * @memberof SignalListResponse
     */
    items?: Array<ClientSignalResponse>;
}

/**
 * Check if a given object implements the SignalListResponse interface.
 */
export function instanceOfSignalListResponse(value: object): value is SignalListResponse {
    return true;
}

export function SignalListResponseFromJSON(json: any): SignalListResponse {
    return SignalListResponseFromJSONTyped(json, false);
}

export function SignalListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignalListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'total': json['total'] == null ? undefined : json['total'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ClientSignalResponseFromJSON)),
    };
}

export function SignalListResponseToJSON(json: any): SignalListResponse {
    return SignalListResponseToJSONTyped(json, false);
}

export function SignalListResponseToJSONTyped(value?: SignalListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'limit': value['limit'],
        'total': value['total'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ClientSignalResponseToJSON)),
    };
}

