/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BackupJobProvider } from './BackupJobProvider';
import {
    BackupJobProviderFromJSON,
    BackupJobProviderFromJSONTyped,
    BackupJobProviderToJSON,
    BackupJobProviderToJSONTyped,
} from './BackupJobProvider';
import type { BackupJobType } from './BackupJobType';
import {
    BackupJobTypeFromJSON,
    BackupJobTypeFromJSONTyped,
    BackupJobTypeToJSON,
    BackupJobTypeToJSONTyped,
} from './BackupJobType';

/**
 * 
 * @export
 * @interface UpdateAutoBackupJson
 */
export interface UpdateAutoBackupJson {
    /**
     * 
     * @type {BackupJobType}
     * @memberof UpdateAutoBackupJson
     */
    type?: BackupJobType;
    /**
     * 
     * @type {BackupJobProvider}
     * @memberof UpdateAutoBackupJson
     */
    provider?: BackupJobProvider;
    /**
     * Provider-specific backup job configuration
     * @type {object}
     * @memberof UpdateAutoBackupJson
     */
    config?: object;
    /**
     * Required when type is 'agent'
     * @type {string}
     * @memberof UpdateAutoBackupJson
     */
    agent_id?: string;
    /**
     * Required when type is 'worker'
     * @type {string}
     * @memberof UpdateAutoBackupJson
     */
    zone?: string;
    /**
     * Cron expression for scheduled execution
     * @type {string}
     * @memberof UpdateAutoBackupJson
     */
    schedule?: string;
}



/**
 * Check if a given object implements the UpdateAutoBackupJson interface.
 */
export function instanceOfUpdateAutoBackupJson(value: object): value is UpdateAutoBackupJson {
    return true;
}

export function UpdateAutoBackupJsonFromJSON(json: any): UpdateAutoBackupJson {
    return UpdateAutoBackupJsonFromJSONTyped(json, false);
}

export function UpdateAutoBackupJsonFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAutoBackupJson {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : BackupJobTypeFromJSON(json['type']),
        'provider': json['provider'] == null ? undefined : BackupJobProviderFromJSON(json['provider']),
        'config': json['config'] == null ? undefined : json['config'],
        'agent_id': json['agent_id'] == null ? undefined : json['agent_id'],
        'zone': json['zone'] == null ? undefined : json['zone'],
        'schedule': json['schedule'] == null ? undefined : json['schedule'],
    };
}

export function UpdateAutoBackupJsonToJSON(json: any): UpdateAutoBackupJson {
    return UpdateAutoBackupJsonToJSONTyped(json, false);
}

export function UpdateAutoBackupJsonToJSONTyped(value?: UpdateAutoBackupJson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': BackupJobTypeToJSON(value['type']),
        'provider': BackupJobProviderToJSON(value['provider']),
        'config': value['config'],
        'agent_id': value['agent_id'],
        'zone': value['zone'],
        'schedule': value['schedule'],
    };
}

