/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowExecution } from './WorkflowExecution';
import {
    WorkflowExecutionFromJSON,
    WorkflowExecutionFromJSONTyped,
    WorkflowExecutionToJSON,
    WorkflowExecutionToJSONTyped,
} from './WorkflowExecution';

/**
 * 
 * @export
 * @interface WorkflowExecutionListResponse
 */
export interface WorkflowExecutionListResponse {
    /**
     * 
     * @type {Array<WorkflowExecution>}
     * @memberof WorkflowExecutionListResponse
     */
    executions?: Array<WorkflowExecution>;
}

/**
 * Check if a given object implements the WorkflowExecutionListResponse interface.
 */
export function instanceOfWorkflowExecutionListResponse(value: object): value is WorkflowExecutionListResponse {
    return true;
}

export function WorkflowExecutionListResponseFromJSON(json: any): WorkflowExecutionListResponse {
    return WorkflowExecutionListResponseFromJSONTyped(json, false);
}

export function WorkflowExecutionListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowExecutionListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'executions': json['executions'] == null ? undefined : ((json['executions'] as Array<any>).map(WorkflowExecutionFromJSON)),
    };
}

export function WorkflowExecutionListResponseToJSON(json: any): WorkflowExecutionListResponse {
    return WorkflowExecutionListResponseToJSONTyped(json, false);
}

export function WorkflowExecutionListResponseToJSONTyped(value?: WorkflowExecutionListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executions': value['executions'] == null ? undefined : ((value['executions'] as Array<any>).map(WorkflowExecutionToJSON)),
    };
}

